sonar.projectKey=qr-service
sonar.projectName=QR Service

# Path to your source code directory
sonar.sources=src

# Exclude coverage, dist, and tests from being analyzed as source code
sonar.exclusions=dist/**,node_modules/**,coverage/**,**/*.test.ts,**/*.spec.ts

# Path to your test directory
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts